# Práctica 1
Generación y Validación de un Dataset Clínico Simulado
Materia: Extracción de Conocimientos en Base de Datos

Alumno: Jesús Antonio Estrada Jiménez 

Objetivo:

Generar, validar y analizar un dataset clínico simulado de 5,000 pacientes generales del estado de Puebla mediante técnicas de limpieza, verificación y análisis exploratorio de datos (EDA) utilizando Python.

Importación de librerías

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Mostrar todas las columnas
pd.set_option("display.max_columns", None)

# Mostrar dos decimales
pd.options.display.float_format = "{:.2f}".format

# Tamaño de las gráficas
plt.rcParams["figure.figsize"] = (10,6)

# Cargar Dataset

In [2]:
ruta = "../dataset/pacientes_diabetes_puebla.csv"

df = pd.read_csv(ruta)

df.head()

,ID,Edad,Sexo,Municipio,Tiene_Diabetes,Tipo_Diabetes,Anios_Diagnostico,Peso_kg,Estatura_m,IMC,Glucosa_Ayuno,HbA1c,TA_Sis,TA_Dia,Colesterol,Trigliceridos,Actividad_Fisica,Fumador,Hipertension,Obesidad,Tratamiento,Fecha_Consulta
0,1,40,F,Tlaola,Sí,Tipo 2,14,117.00,1.59,46.30,231,7.40,140,106,177,295,Media,Sí,Sí,Sí,Sulfonilurea,2023-12-07
1,2,60,M,Xochiapulco,No,No aplica,0,48.20,1.88,13.60,87,5.70,157,110,188,210,Baja,No,Sí,No,Ninguno,2023-06-21
2,3,67,F,San Miguel Xoxtla,No,No aplica,0,49.80,1.81,15.20,90,4.90,117,70,154,121,Media,Sí,No,No,Ninguno,2024-08-08
3,4,68,M,Izúcar de Matamoros,Sí,Tipo 2,17,63.00,1.70,21.80,128,10.20,121,62,245,147,Media,No,No,No,Sulfonilurea,2024-04-24
4,5,27,F,Zoquitlán,No,No aplica,0,68.30,1.86,19.70,75,5.40,128,63,211,276,Baja,No,No,No,Ninguno,2024-07-07

## 4 Vista previa del dataset

In [3]:
df.head()

,ID,Edad,Sexo,Municipio,Tiene_Diabetes,Tipo_Diabetes,Anios_Diagnostico,Peso_kg,Estatura_m,IMC,Glucosa_Ayuno,HbA1c,TA_Sis,TA_Dia,Colesterol,Trigliceridos,Actividad_Fisica,Fumador,Hipertension,Obesidad,Tratamiento,Fecha_Consulta
0,1,40,F,Tlaola,Sí,Tipo 2,14,117.00,1.59,46.30,231,7.40,140,106,177,295,Media,Sí,Sí,Sí,Sulfonilurea,2023-12-07
1,2,60,M,Xochiapulco,No,No aplica,0,48.20,1.88,13.60,87,5.70,157,110,188,210,Baja,No,Sí,No,Ninguno,2023-06-21
2,3,67,F,San Miguel Xoxtla,No,No aplica,0,49.80,1.81,15.20,90,4.90,117,70,154,121,Media,Sí,No,No,Ninguno,2024-08-08
3,4,68,M,Izúcar de Matamoros,Sí,Tipo 2,17,63.00,1.70,21.80,128,10.20,121,62,245,147,Media,No,No,No,Sulfonilurea,2024-04-24
4,5,27,F,Zoquitlán,No,No aplica,0,68.30,1.86,19.70,75,5.40,128,63,211,276,Baja,No,No,No,Ninguno,2024-07-07

# 5. Verificar Dimensiones

## 5.1 Verificación de las dimensiones del dataset

Se verifica el número de filas y columnas del dataset para confirmar que contiene la cantidad esperada de registros y atributos.

In [4]:
print(f"Número de filas: {df.shape[0]}")
print(f"Número de columnas: {df.shape[1]}")

Número de filas: 5000
Número de columnas: 22